### PR TITLE
add image mimetypes

### PR DESCRIPTION
**Pull request by tanan**
**Describe the PR**
add mime type for comsumes and aproduces
- image/png
- image/jpeg
- image/gif

**Relation issue**
https://github.com/swaggo/swaggo.io/issues/15

### CODE REVIEW

**Review by easonlin404 — APPROVED** [review]

**Comment by easonlin404** [comment]
@pei0804 Any idea why ci build failed?

**Comment by pei0804** [comment]
I will fix it later
There is no problem with this commit.

**Comment by easonlin404** [comment]
@tanan thanks for your contributions 💯

**Comment by tanan** [comment]
@easonlin404 @pei0804  thanks for your supports

**Pull request merged**
